### ISSUE TITLE
cbpi should be removed from setup.py install requires

### ISSUE THREAD

**Issue by avollkopf** [kmarkley/cbpi4-KM_Personal_Plugins#1]
you should remove cbpi from the 'install_requires' in setup.py as most recent package name has changed to cbpi4

**Comment by kmarkley** [comment]
Thanks.  Pretty sure I cribbed that file from one of your repositories and never noticed that.  Fixed now.

Also added a couple comments to describe the plugin classes.

**Comment by avollkopf** [comment]
was ok at that time. I just had to change the package name to release it on pypi.org. Manuel is not really active and I can't release packages with the same name :-(

**Comment by avollkopf** [comment]
Now you can also install the latest cbpi4 directly from pyip.org via udo pip install cbpi4 

https://pypi.org/project/cbpi4/
